import { useState, useEffect } from 'react';
import { ShieldCheck, Loader2 } from 'lucide-react';

export default function TwoFactorToggle() {
  const [isEnabled, setIsEnabled] = useState(false);
  const [isSettingUp, setIsSettingUp] = useState(false);
  const [qrCodeUri, setQrCodeUri] = useState('');
  const [secret, setSecret] = useState('');
  const [otp, setOtp] = useState('');
  const [loading, setLoading] = useState(true);
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    // Fetch initial profile to check if 2FA is already enabled
    fetch('http://localhost:5000/api/profile', { credentials: 'include' })
      .then(res => res.json())
      .then(data => {
        setIsEnabled(data.two_factor_enabled || false);
      })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const handleToggle = async () => {
    if (isEnabled) {
      // In a real app we might verify before disabling, but skipping for demo simplicity
      // since backend doesn't have an explicit disable endpoint requested, 
      // but assuming it's unchangeable or requires contact. 
      // User requested "Only then enable 2FA" -> we just handle enable flow.
      return;
    }
    
    if (isSettingUp) {
      setIsSettingUp(false);
      return;
    }

    try {
      const res = await fetch('http://localhost:5000/api/security/enable-2fa', {
        method: 'POST',
        credentials: 'include'
      });
      const data = await res.json();
      if (res.ok) {
        setSecret(data.secret);
        setQrCodeUri(data.otp_uri);
        setIsSettingUp(true);
      } else {
        setError(data.message || 'Failed to start setup');
      }
    } catch (err) {
      setError('Connection error');
    }
  };

  const handleVerify = async () => {
    if (!otp || otp.length < 6) return;
    setVerifying(true);
    setError('');

    try {
      const res = await fetch('http://localhost:5000/api/security/verify-2fa', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ otp })
      });
      const data = await res.json();
      
      if (res.ok) {
        setIsEnabled(true);
        setIsSettingUp(false);
      } else {
        setError(data.message || 'Invalid verification code');
      }
    } catch (err) {
      setError('Connection error');
    } finally {
      setVerifying(false);
    }
  };

  if (loading) return null;

  return (
    <div className="bg-[#151E18] border border-[#1C2A22] rounded-2xl p-6 sm:p-8">
      <div className="flex items-center gap-3 mb-6">
        <ShieldCheck className="w-6 h-6 text-neon-green" />
        <h2 className="text-xl font-bold">Two-Factor Authentication</h2>
      </div>

      <div className="flex justify-between items-start sm:items-center flex-col sm:flex-row gap-4">
        <div>
          <p className="text-gray-300 text-sm max-w-lg mb-1">
            Secure your account by requiring an additional verification step. We recommend using an authenticator app for the highest level of security.
          </p>
        </div>
        
        {/* Toggle Switch */}
        <button 
          onClick={handleToggle}
          disabled={isEnabled} // Prevent disabling for now as it wasn't specified in requirements
          className={`relative inline-flex h-7 w-12 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${isEnabled ? 'bg-neon-green' : 'bg-[#1C2A22]'}`}
        >
          <span className={`pointer-events-none inline-block h-6 w-6 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${isEnabled ? 'translate-x-5' : 'translate-x-0'}`} />
        </button>
      </div>

      {isSettingUp && (
        <div className="mt-8 pt-8 border-t border-[#1C2A22] animate-slide-down">
          <h3 className="text-lg font-bold mb-4">Setup Authenticator App</h3>
          <ol className="list-decimal list-inside text-sm text-gray-400 space-y-3 mb-6">
            <li>Download Google Authenticator or Authy on your mobile device.</li>
            <li>Scan the QR code below or enter the setup key manually.</li>
            <li>Enter the 6-digit code generated by the app.</li>
          </ol>

          {error && <p className="text-red-400 text-sm mb-4">{error}</p>}

          <div className="flex flex-col md:flex-row items-center gap-8 mb-6">
            <div className="bg-white p-4 rounded-xl inline-block">
              {/* Using a public API to generate simple QR code from URI (for frontend simplicity) */}
              <img src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(qrCodeUri)}`} alt="QR Code" width="150" height="150" />
            </div>
            
            <div className="w-full max-w-xs">
              <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Setup Key</label>
              <div className="bg-[#121A15] p-3 rounded-lg border border-[#1C2A22] font-mono text-neon-green mb-6 select-all">
                {secret}
              </div>

              <label className="block text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Verification Code</label>
              <div className="flex gap-3">
                <input
                  type="text"
                  maxLength="6"
                  placeholder="000000"
                  value={otp}
                  onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))}
                  className="w-full bg-[#121A15] border border-[#1C2A22] text-white rounded-xl px-4 py-3 focus:outline-none focus:border-neon-green/50 text-center tracking-[0.5em] font-mono text-lg"
                />
                <button 
                  onClick={handleVerify}
                  disabled={verifying || otp.length < 6}
                  className="bg-neon-green text-black px-6 py-3 rounded-xl font-bold hover:bg-neon-green-hover transition-all disabled:opacity-70 flex items-center justify-center shrink-0"
                >
                  {verifying ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Verify'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
